import { createClient } from "@libsql/client";

// Exact DDL generated by: prisma migrate diff --from-empty --to-schema prisma/schema.prisma --script
const SCHEMA_SQL = [
  `CREATE TABLE IF NOT EXISTS "AppSettings" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT 'singleton',
    "smtpHost" TEXT NOT NULL DEFAULT '',
    "smtpPort" INTEGER NOT NULL DEFAULT 587,
    "smtpUser" TEXT NOT NULL DEFAULT '',
    "smtpPass" TEXT NOT NULL DEFAULT '',
    "smtpFrom" TEXT NOT NULL DEFAULT ''
  )`,
  `CREATE TABLE IF NOT EXISTS "Product" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "asin" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "image" TEXT,
    "url" TEXT NOT NULL,
    "currentPrice" REAL,
    "targetPrice" REAL,
    "lastChecked" DATETIME,
    "notified" BOOLEAN NOT NULL DEFAULT false,
    "inStock" BOOLEAN NOT NULL DEFAULT true,
    "trackStock" BOOLEAN NOT NULL DEFAULT false,
    "stockNotified" BOOLEAN NOT NULL DEFAULT false,
    "includeSecondHand" BOOLEAN NOT NULL DEFAULT true,
    "availableSellers" TEXT NOT NULL DEFAULT '[]',
    "excludedSellers" TEXT NOT NULL DEFAULT '[]',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "Product_asin_key" ON "Product"("asin")`,
];

// Columns added after the initial schema — silently ignored if already present
const BACKFILL_COLUMNS = [
  `ALTER TABLE "Product" ADD COLUMN "trackStock" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "Product" ADD COLUMN "stockNotified" BOOLEAN NOT NULL DEFAULT false`,
  `ALTER TABLE "Product" ADD COLUMN "includeSecondHand" BOOLEAN NOT NULL DEFAULT true`,
  `ALTER TABLE "Product" ADD COLUMN "availableSellers" TEXT NOT NULL DEFAULT '[]'`,
  `ALTER TABLE "Product" ADD COLUMN "excludedSellers" TEXT NOT NULL DEFAULT '[]'`,
];

export async function runMigrations(): Promise<void> {
  const url = process.env.DATABASE_URL ?? "";
  const client = createClient({ url });
  try {
    for (const sql of SCHEMA_SQL) {
      await client.execute(sql);
    }
    for (const sql of BACKFILL_COLUMNS) {
      await client.execute(sql).catch(() => {
        // duplicate column — already applied
      });
    }
    console.log("[migrate] Schema up to date");
  } finally {
    client.close();
  }
}
