import { createClient } from "@libsql/client";

// Exact DDL generated by: prisma migrate diff --from-empty --to-schema prisma/schema.prisma --script
const SCHEMA_SQL = [
  `CREATE TABLE IF NOT EXISTS "AppSettings" (
    "id" TEXT NOT NULL PRIMARY KEY DEFAULT 'singleton',
    "smtpHost" TEXT NOT NULL DEFAULT '',
    "smtpPort" INTEGER NOT NULL DEFAULT 587,
    "smtpUser" TEXT NOT NULL DEFAULT '',
    "smtpPass" TEXT NOT NULL DEFAULT '',
    "smtpFrom" TEXT NOT NULL DEFAULT ''
  )`,
  `CREATE TABLE IF NOT EXISTS "Product" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "asin" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "image" TEXT,
    "url" TEXT NOT NULL,
    "currentPrice" REAL,
    "targetPrice" REAL,
    "lastChecked" DATETIME,
    "notified" BOOLEAN NOT NULL DEFAULT false,
    "inStock" BOOLEAN NOT NULL DEFAULT true,
    "trackStock" BOOLEAN NOT NULL DEFAULT false,
    "stockNotified" BOOLEAN NOT NULL DEFAULT false,
    "includeSecondHand" BOOLEAN NOT NULL DEFAULT true,
    "availableSellers" TEXT NOT NULL DEFAULT '[]',
    "excludedSellers" TEXT NOT NULL DEFAULT '[]',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS "Product_asin_key" ON "Product"("asin")`,
];

export async function runMigrations(): Promise<void> {
  const url = process.env.DATABASE_URL ?? "";
  const client = createClient({ url });
  try {
    for (const sql of SCHEMA_SQL) {
      await client.execute(sql);
    }
    console.log("[migrate] Schema up to date");
  } finally {
    client.close();
  }
}
